sbatch SVM_Train_Model_1.sh
sbatch SVM_Train_Model_2.sh
sbatch SVM_Train_Model_3.sh
sbatch SVM_Train_Model_4.sh
sbatch SVM_Train_Model_5.sh
sbatch SVM_Train_Model_6.sh
sbatch SVM_Train_Model_7.sh
sbatch SVM_Train_Model_8.sh
sbatch SVM_Train_Model_9.sh
sbatch SVM_Train_Model_10.sh
sbatch SVM_Train_Model_11.sh
sbatch SVM_Train_Model_12.sh
sbatch SVM_Train_Model_13.sh
sbatch SVM_Train_Model_14.sh
sbatch SVM_Train_Model_15.sh
sbatch SVM_Train_Model_16.sh
sbatch SVM_Train_Model_17.sh
sbatch SVM_Train_Model_18.sh
sbatch SVM_Train_Model_19.sh
sbatch SVM_Train_Model_20.sh
sbatch SVM_Train_Model_21.sh
sbatch SVM_Train_Model_22.sh
sbatch SVM_Train_Model_23.sh
sbatch SVM_Train_Model_24.sh
sbatch SVM_Train_Model_25.sh
sbatch SVM_Train_Model_26.sh
sbatch SVM_Train_Model_27.sh
sbatch SVM_Train_Model_28.sh
sbatch SVM_Train_Model_29.sh
sbatch SVM_Train_Model_30.sh
sbatch SVM_Train_Model_31.sh
sbatch SVM_Train_Model_32.sh
sbatch SVM_Train_Model_33.sh
sbatch SVM_Train_Model_34.sh
sbatch SVM_Train_Model_35.sh
sbatch SVM_Train_Model_36.sh
sbatch SVM_Train_Model_37.sh
sbatch SVM_Train_Model_38.sh
sbatch SVM_Train_Model_39.sh
sbatch SVM_Train_Model_40.sh
sbatch SVM_Train_Model_41.sh
sbatch SVM_Train_Model_42.sh
sbatch SVM_Train_Model_43.sh
sbatch SVM_Train_Model_44.sh
sbatch SVM_Train_Model_45.sh
sbatch SVM_Train_Model_46.sh
