sbatch SVM_Train_Model_1.sh
sbatch SVM_Train_Model_2.sh
sbatch SVM_Train_Model_3.sh
sbatch SVM_Train_Model_4.sh
sbatch SVM_Train_Model_5.sh
sbatch SVM_Train_Model_6.sh
sbatch SVM_Train_Model_7.sh
sbatch SVM_Train_Model_8.sh
sbatch SVM_Train_Model_9.sh
sbatch SVM_Train_Model_10.sh
sbatch SVM_Train_Model_11.sh
sbatch SVM_Train_Model_12.sh
sbatch SVM_Train_Model_13.sh
sbatch SVM_Train_Model_14.sh
sbatch SVM_Train_Model_15.sh
sbatch SVM_Train_Model_16.sh
sbatch SVM_Train_Model_17.sh
sbatch SVM_Train_Model_18.sh
sbatch SVM_Train_Model_19.sh
sbatch SVM_Train_Model_20.sh
sbatch SVM_Train_Model_21.sh
sbatch SVM_Train_Model_22.sh
sbatch SVM_Train_Model_23.sh
sbatch SVM_Train_Model_24.sh
sbatch SVM_Train_Model_25.sh
sbatch SVM_Train_Model_26.sh
sbatch SVM_Train_Model_27.sh
sbatch SVM_Train_Model_28.sh
sbatch SVM_Train_Model_29.sh
sbatch SVM_Train_Model_30.sh
sbatch SVM_Train_Model_31.sh
sbatch SVM_Train_Model_32.sh
sbatch SVM_Train_Model_33.sh
sbatch SVM_Train_Model_34.sh
sbatch SVM_Train_Model_35.sh
sbatch SVM_Train_Model_36.sh
sbatch SVM_Train_Model_37.sh
sbatch SVM_Train_Model_38.sh
sbatch SVM_Train_Model_39.sh
sbatch SVM_Train_Model_40.sh
sbatch SVM_Train_Model_41.sh
sbatch SVM_Train_Model_42.sh
sbatch SVM_Train_Model_43.sh
sbatch SVM_Train_Model_44.sh
sbatch SVM_Train_Model_45.sh
sbatch SVM_Train_Model_46.sh
sbatch SVM_Train_Model_47.sh
sbatch SVM_Train_Model_48.sh
sbatch SVM_Train_Model_49.sh
sbatch SVM_Train_Model_50.sh
sbatch SVM_Train_Model_51.sh
sbatch SVM_Train_Model_52.sh
sbatch SVM_Train_Model_53.sh
sbatch SVM_Train_Model_54.sh
sbatch SVM_Train_Model_55.sh
sbatch SVM_Train_Model_56.sh
sbatch SVM_Train_Model_57.sh
sbatch SVM_Train_Model_58.sh
sbatch SVM_Train_Model_59.sh
sbatch SVM_Train_Model_60.sh
sbatch SVM_Train_Model_61.sh
sbatch SVM_Train_Model_62.sh
sbatch SVM_Train_Model_63.sh
sbatch SVM_Train_Model_64.sh
sbatch SVM_Train_Model_65.sh
sbatch SVM_Train_Model_66.sh
sbatch SVM_Train_Model_67.sh
sbatch SVM_Train_Model_68.sh
sbatch SVM_Train_Model_69.sh
sbatch SVM_Train_Model_70.sh
sbatch SVM_Train_Model_71.sh
sbatch SVM_Train_Model_72.sh
sbatch SVM_Train_Model_73.sh
sbatch SVM_Train_Model_74.sh
sbatch SVM_Train_Model_75.sh
sbatch SVM_Train_Model_76.sh
sbatch SVM_Train_Model_77.sh
sbatch SVM_Train_Model_78.sh
sbatch SVM_Train_Model_79.sh
sbatch SVM_Train_Model_80.sh
sbatch SVM_Train_Model_81.sh
sbatch SVM_Train_Model_82.sh
sbatch SVM_Train_Model_83.sh
sbatch SVM_Train_Model_84.sh
sbatch SVM_Train_Model_85.sh
sbatch SVM_Train_Model_86.sh
sbatch SVM_Train_Model_87.sh
sbatch SVM_Train_Model_88.sh
sbatch SVM_Train_Model_89.sh
sbatch SVM_Train_Model_90.sh
sbatch SVM_Train_Model_91.sh
sbatch SVM_Train_Model_92.sh

