sbatch runASL_Train1.sh
sbatch runASL_Train2.sh
sbatch runASL_Train3.sh
sbatch runASL_Train4.sh
sbatch runASL_Train5.sh
sbatch runASL_Train6.sh
sbatch runASL_Train7.sh
sbatch runASL_Train8.sh
sbatch runASL_Train9.sh
sbatch runASL_Train10.sh
sbatch runASL_Train11.sh
sbatch runASL_Train12.sh
sbatch runASL_Train13.sh
sbatch runASL_Train14.sh
sbatch runASL_Train15.sh
sbatch runASL_Train16.sh
sbatch runASL_Train17.sh
sbatch runASL_Train18.sh
sbatch runASL_Train19.sh
sbatch runASL_Train20.sh
sbatch runASL_Train21.sh
sbatch runASL_Train22.sh
sbatch runASL_Train23.sh
sbatch runASL_Train24.sh
sbatch runASL_Train25.sh
sbatch runASL_Train26.sh
sbatch runASL_Train27.sh
